export const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
